# -*- coding: utf-8 -*-
"""Lab_Data_Centric_AI_vs_Model_Centric_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y0YaF64Tp4VD4vDuIrQxYYDHxrXEQrbs

# Lab: Sentiment Analysis  
#  *******Data-Centric vs Model-Centric approaches




This lab gives an introduction to sentiment analysis approaches.

In this lab, we'll build a classifier for product reviews (restricted to the magazine category), like:

> Excellent! I look forward to every issue. I had no idea just how much I didn't know.  The letters from the subscribers are educational, too.

Label: ⭐️⭐️⭐️⭐️⭐️ (good)

> My son waited and waited, it took the 6 weeks to get delivered that they said it would but when it got here he was so dissapointed, it only took him a few minutes to read it.

Label: ⭐️ (bad)

We'll work with a dataset that has some issues, and we'll see how we can squeeze only so much performance out of the model by being clever about model choice, searching for better hyperparameters, etc. Then, we'll take a look at the data (as any good data scientist should), develop an understanding of the issues, and use simple approaches to improve the data. Finally, we'll see how improving the data can improve results.

## Installing software

For this lab, you'll need to install [scikit-learn](https://scikit-learn.org/) and [pandas](https://pandas.pydata.org/). If you don't have them installed already, you can install them by running the following cell:
"""

!pip install scikit-learn pandas

"""# Loading the data

First, let's load the train/test sets and take a look at the data.
"""

import pandas as pd

train = pd.read_csv('reviews_train.csv')
test = pd.read_csv('reviews_test.csv')

import pandas as pd

train = pd.read_csv('reviews_train.csv')
test = pd.read_csv('reviews_test.csv')

test.sample(5)

"""# Training a baseline model

There are many approaches for training a sequence classification model for text data. In this lab, we're giving you code that mirrors what you find if you look up [how to train a text classifier](https://scikit-learn.org/stable/tutorial/text_analytics/working_with_text_data.html), where we'll train an SVM on [tf-idf](https://en.wikipedia.org/wiki/Tf%E2%80%93idf) features (numeric representations of each text field based on word occurrences).
"""

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import Pipeline

sgd_clf = Pipeline([
    ('vect', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('clf', SGDClassifier()),
])

_ = sgd_clf.fit(train['review'], train['label'])

"""## Evaluating model accuracy"""

from sklearn import metrics

def evaluate(clf):
    pred = clf.predict(test['review'])
    acc = metrics.accuracy_score(test['label'], pred)
    print(f'Accuracy: {100*acc:.1f}%')

from sklearn import metrics

def evaluate(clf):
    pred = clf.predict(test['review'])
    acc = metrics.accuracy_score(test['label'], pred)
    print(f'Accuracy: {100*acc:.1f}%')

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.linear_model import LogisticRegression

better_model = Pipeline([
    ('vect', CountVectorizer(ngram_range=(1,2), stop_words='english', min_df=2)),
    ('tfidf', TfidfTransformer()),
    ('clf', LogisticRegression(max_iter=2000)),
])

better_model.fit(train['review'], train['label'])
evaluate(better_model)

better_model = Pipeline([
    ('vect', CountVectorizer(ngram_range=(1,2), stop_words='english', max_features=10000)),
    ('tfidf', TfidfTransformer()),
    ('clf', LogisticRegression(max_iter=2000)),
])

better_model.fit(train_clean['review'], train_clean['label'])
evaluate(better_model)

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.metrics import accuracy_score

from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression, SGDClassifier

models = {
    "KNeighbors": KNeighborsClassifier(),
    "LinearSVC": LinearSVC(),
    "DecisionTree": DecisionTreeClassifier(random_state=42),
    "RandomForest": RandomForestClassifier(random_state=42),
    "AdaBoost": AdaBoostClassifier(random_state=42),
    "MultinomialNB": MultinomialNB(),
    "MLP": MLPClassifier(max_iter=1000, random_state=42),
    "LogisticRegression": LogisticRegression(max_iter=2000),
    "SGDClassifier": SGDClassifier(random_state=42),
}

results = []

for name, model in models.items():
    clf = Pipeline([
        ('vect', CountVectorizer(ngram_range=(1,2), stop_words='english', min_df=2)),
        ('tfidf', TfidfTransformer()),
        ('clf', model),
    ])

    clf.fit(train['review'], train['label'])
    pred = clf.predict(test['review'])
    acc = accuracy_score(test['label'], pred)

    results.append((name, acc))
    print(f"{name}: {acc*100:.2f}%")

best_model = max(results, key=lambda x: x[1])
print("\nBest model:", best_model[0], f"with accuracy {best_model[1]*100:.2f}%")

from sklearn import metrics

def evaluate(clf):
    pred = clf.predict(test['review'])
    acc = metrics.accuracy_score(test['label'], pred)
    print(f'Accuracy: {100*acc:.1f}%')

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.naive_bayes import MultinomialNB

nb_clf = Pipeline([
    ('vect', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('clf', MultinomialNB()),
])

nb_clf.fit(train['review'], train['label'])
evaluate(nb_clf)

from sklearn.linear_model import LogisticRegression

lr_clf = Pipeline([
    ('vect', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('clf', LogisticRegression(max_iter=2000)),
])

lr_clf.fit(train['review'], train['label'])
evaluate(lr_clf)

print('Fitting sgd_clf on original training data...')
_ = sgd_clf.fit(train['review'], train['label'])
print('sgd_clf fitted.')

"""Now that both models are fitted, let's generate their confusion matrices on the test set."""

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

def plot_confusion_matrix(model, X_test, y_test, title):
    y_pred = model.predict(X_test)
    cm = confusion_matrix(y_test, y_pred, labels=model.classes_)

    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=model.classes_, yticklabels=model.classes_)
    plt.title(title)
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')
    plt.show()


print('Generating confusion matrix for better_model...')
plot_confusion_matrix(better_model, test['review'], test['label'], 'Confusion Matrix for Better Model')

print('Generating confusion matrix for sgd_clf...')
plot_confusion_matrix(sgd_clf, test['review'], test['label'], 'Confusion Matrix for SGDClassifier')

"""The confusion matrices above provide a detailed breakdown of the true positives, true negatives, false positives, and false negatives for each model.

**For the `SGDClassifier` (sgd_clf) trained on the original, uncleaned data:**
*   You'll likely observe a higher number of misclassifications, especially false positives and false negatives, compared to the `better_model`. This is because the uncleaned data contains noise (like HTML tags and wrongly labeled reviews) that can confuse the model.

**For the `better_model` (Logistic Regression) trained on the cleaned data (`train_clean`):**
*   The confusion matrix should show a clearer diagonal, indicating more accurate predictions. The false positives and false negatives should be significantly lower, reflecting the improved performance due to data cleaning and potentially better hyperparameter tuning/model choice.

This visualization clearly demonstrates the impact of data quality and model tuning on classification performance.

## Trying another model

76% accuracy is not great for this binary classification problem. Can you do better with a different model, or by tuning hyperparameters for the SVM trained with SGD?

# Exercise 1

Can you train a more accurate model on the dataset (without changing the dataset)? You might find this [scikit-learn classifier comparison](https://scikit-learn.org/stable/auto_examples/classification/plot_classifier_comparison.html) handy, as well as the [documentation for supervised learning in scikit-learn](https://scikit-learn.org/stable/supervised_learning.html).

One idea for a model you could try is a [naive Bayes classifier](https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html).

You could also try experimenting with different values of the model hyperparameters, perhaps tuning them via a [grid search](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html).

Or you can even try training multiple different models and [ensembling their predictions](https://scikit-learn.org/stable/modules/ensemble.html#voting-classifier), a strategy often used to win prediction competitions like Kaggle.

**Advanced:** If you want to be more ambitious, you could try an even fancier model, like training a Transformer neural network. If you go with that, you'll want to fine-tune a pre-trained model. This [guide from HuggingFace](https://huggingface.co/docs/transformers/training) may be helpful.
"""

# YOUR CODE HERE
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.linear_model import SGDClassifier

sgd_clf = Pipeline([
    ('vect', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('clf', SGDClassifier()),
])
# evaluate your model and see if it does better
# than the ones we provided

"""## Taking a closer look at the training data

Let's actually take a look at some of the training data:
"""

train.head()

"""Zooming in on one particular data point:"""

print(train.iloc[0].to_dict())

"""This data point is labeled "good", but it's clearly a negative review. Also, it looks like there's some funny HTML stuff at the end.

# Exercise 2

Take a look at some more examples in the dataset. Do you notice any patterns with bad data points?
"""

# YOUR CODE HERE
train.sample(10)

"""Look at this:

Review says: “I have not received anything…” → clearly negative
But label = good

That’s a wrong label

3. Delivery/service complaints (not product sentiment)

Examples:

“Still have not received anything”
“Ordered this in Nov…”

These are about:

shipping
delays

NOT about the product itself → confusing for the model

4. Strong negative language (correct but noisy)

Examples:

“Disgusting, bigoted trash…”
“boring magazine”

 These are fine but:

very emotional
may bias the model


I noticed several patterns in the bad data points. Some reviews contain HTML tags, which suggests the data was scraped and not properly cleaned. These tags introduce noise and are not useful for sentiment analysis. I also observed cases where the label does not match the actual sentiment of the review, such as negative reviews labeled as “good.” Additionally, many reviews focus on delivery or service issues rather than the product itself, which can confuse the model. Overall, these issues indicate that the dataset contains noise and labeling errors.

## Issues in the data

It looks like there's some funny HTML tags in our dataset, and those datapoints have nonsense labels. Maybe this dataset was collected by scraping the internet, and the HTML wasn't quite parsed correctly in all cases.

What patterns are visible
1. HTML tags in reviews

Example:

<div class="description">As of 4/6 I have not ...

 This is bad data

It comes from web scraping
It adds noise
It doesn’t help sentiment analysis

# Exercise 3

To address this, a simple approach we might try is to throw out the bad data points, and train our model on only the "clean" data.

Come up with a simple heuristic to identify data points containing HTML, and filter out the bad data points to create a cleaned training set.
"""

def is_bad_data(review: str) -> bool:
    return '<' in review and '>' in review

"""## Creating the cleaned training set"""

train_clean = train[~train['review'].map(is_bad_data)]

"""## Evaluating a model trained on the clean training set"""

from sklearn import clone

sgd_clf_clean = clone(sgd_clf)

_ = sgd_clf_clean.fit(train_clean['review'], train_clean['label'])

"""This model should do significantly better:"""

evaluate(sgd_clf_clean)